######################################################################
# Automatically generated by qmake (2.01a) Pzt May 14 16:17:43 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp

QMAKE_CXXFLAGS += -std=c++11
